#Spring Boot 설정!!
spring:
  #Spring Boot 로그
  output:
    ansi:
      enabled: always

  #DataBase(MySQL) 설정
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/examplesdb?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: urstory
    password: u1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      connection-test-query: SELECT NOW() FROM dual

# Mybatis 설정
mybatis:
  type-aliases-package: com.example.basic.model.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
# mybatis:
#   # default Package location - resultType의 Alias를 지정합니다.
#   type-aliases-package: com.example.basic.model
#   # mapper location - 바라 볼 xml 파일을 지정합니다.
#   mapper-locations: classpath:mapper/**/*.xml
#   # column name to camel case - 반환 받는 컬럼명을 CamelCase로 받는 설정을 합니다.
#   configuration:
#     map-underscore-to-camel-case: true
